odbedit -c "mkdir custom"
odbedit -c "create string custom/FPGASettings"
odbedit -c "create string custom/DigiSettings"
odbedit -c "create string custom/FrequencyMeter"
odbedit -c "set \"custom/FPGASettings\" \"/home/neatdaq/NewDaq/development/frontend/both/resources/fpgasettings.html\""
odbedit -c "set \"custom/FrequencyMeter\" \"/home/neatdaq/NewDaq/development/ongithub/NeatFrequencyMeter/frontend/resources/frequencymeter.html\""
odbedit -c "set \"custom/DigiSettings\" \"/home/neatdaq/NewDaq/development/frontend/both/resources/digisettings.html\""
